name: Compile and package AMXX deliverables
run-name: ${{ github.event.head_commit.message }}
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
      image: stevenlafl/amxmodx-ci
      options: --user root -v ${{ github.workspace }}:/app
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: compile.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compiled
          path: ${{ github.workspace }}/compiled
          runs-on: ubuntu-latest